GameConstants = {
    STATE_MENU = 0,
    STATE_PLAYING = 1,
    STATE_GAMEOVER = 2,

    SCREEN_WIDTH = 400,
    SCREEN_HEIGHT = 240,

    PLAYER_SCALE = 0.05,
    PLAYER_IMAGE_PATH = "assets/Fleur",
    PLAYER_HITBOX_RADIUS = 10,

    POT_IMAGE_PATH = "assets/PotDeFleur",
    
    BACKGROUND_IMAGE_PATH = "assets/BG3",
    BG_PARALLAX_SPEED = 0.2,
    BG_IMAGE_HEIGHT = 240,

    BONUS_SIZE = 30,
    BONUS_SPAWN_INTERVAL = 1000,

    SPEED = 60,
    TURN_RATE = 0.02,
    SMOOTH_DIR = 0.18,
    SCROLL_SPEED = 28,
    MIN_STEP_DISTANCE = 3,
    MAX_STEM_POINTS = 260,
    PATH_SMOOTH = 0.25,
    STEM_RADIUS = 2,

    HEAD_CLAMP_X_MARGIN = 5,
    HEAD_CLAMP_TOP = 10,
    HEAD_CLAMP_BOTTOM_PADDING = 100,

    WATER_HEIGHT = 20,
}
